### ISSUE TITLE
 Library not loaded: libisar.dylib after bumping isar to 3.1.0

### ISSUE THREAD

**Issue by jackstefansky** [isar/isar#1199]
I am getting following error while building for macos after upgrading isar to version 3.1.0

```
dyld[82284]: Library not loaded: /Users/runner/work/isar/isar/target/x86_64-apple-darwin/release/deps/libisar.dylib
  Referenced from: /Users/jackstefansky/Documents/flutter_projects/here_app/build/macos/Build/Products/Debug/HereApp.app/Contents/MacOS/HereApp
  Reason: tried: '/Users/runner/work/isar/isar/target/x86_64-apple-darwin/release/deps/libisar.dylib' (no such file), '/usr/local/lib/libisar.dylib' (no such file), '/usr/lib/libisar.dylib' (no such file)
```

### Details

 - Platform: MacBook Pro 2016, MacOS Monterey 12.2 (21D49)
 - Flutter version: 3.7.0
 - Isar version: 3.1.0

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by jackstefansky** [comment]
My colleague with M1 MacBook Pro is experiencing the same issue

**Comment by bartosz-timecamp** [comment]
I am facing the same issue in the newest version (3.1.0). Everything was working fine in 3.0.5, but after upgrading it to 3.1.0 the macOS version couldn't be built.  Any ideas how to solve this problem?

**Comment by arreshashikant** [comment]
I'm facing relevant issue
```
~/my_app/ios/Runner/GeneratedPluginRegistrant.m:154:9: fatal error: could not build module 'isar_flutter_libs'
    #import <isar_flutter_libs/IsarFlutterLibsPlugin.h>
```

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.2.1 22D68 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/shashi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

**Comment by sbenmeddour** [comment]
Same here, the issue exists since 3.0.6-dev0.

We may have to check what changed between 3.0.5 & 3.0.6 to know what's going wrong

**Comment by CaptainDario** [comment]
I think this is related (or the same) as https://github.com/isar/isar/issues/1112

**Comment by jackstefansky** [comment]
Yeah, it might be, except in my case app does not launch at all

**Comment by anandsubbu007** [comment]
any update on this

**Comment by pauli2406** [comment]
Same issue here, running Macbook with M1 Pro

**Comment by niklasbartsch** [comment]
@tomodian That doesn't work for me with version `isar: ^3.1.0`

**Comment by jackstefansky** [comment]
Thank you @simc. I can confirm this works now :)

**Comment by jackstefansky** [comment]
But I'm still experiencing `IsarError: Cannot open Environment: MdbxError (15): Block device required` on some macos devices.

See #1125
